version: '3.8'

services:
  file-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-monitor
    restart: unless-stopped
    ports:
      - "13030:13030"
    volumes:
      # 모니터링할 호스트 디렉토리를 컨테이너에 마운트
      - ./watch:/app/watch:ro  # 읽기 전용으로 마운트
      - ./logs:/app/logs       # 로그 디렉토리
      - ./data:/app/data       # 캐시 데이터 디렉토리
    env_file:
      - .env
    networks:
      - file-monitor-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  file-monitor-network:
    driver: bridge

volumes:
  file-monitor-logs:
  file-monitor-data: